baseURL = "http://example.org/"
languageCode = "en-us"
title = "翰林國小英語"
theme="ananke"

[frontmatter]
date = ["myDate", ":default"]

[taxonomies]
 tag ="tags"
 category = "categories"
 semester = "semesters"

 
 